server:
  port: 8082

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce_cart
    username: ecommerce_cart_user
    password: CartPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8081}

inventory-service:
  url: ${INVENTORY_SERVICE_URL:http://localhost:8084}

pricing-service:
  url: ${PRICING_SERVICE_URL:http://localhost:8090}

cart:
  cache:
    enabled: true
    ttl-days: 14

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      pricingService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      inventoryService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 2s

