server:
  port: 8082

spring:
  application:
    name: cart-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
    
cart:
  cache:
    enabled: true
    ttl-days: 14

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      pricingService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      inventoryService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 2s

