server:
  port: 8082

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_cart
    username: ecommerce_cart_user
    password: CartPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

product-service:
  url: http://localhost:8081

inventory-service:
  url: http://localhost:8084

pricing-service:
  url: http://localhost:8090

cart:
  cache:
    enabled: true
    ttl-days: 14

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
