server:
  port: 8085

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/customer_db
    username: customer_user
    password: CustomerPass123!
    driver-class-name: org.postgresql.Driver
    
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

  instance:
    prefer-ip-address: true





