server:
  port: 8085

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://postgres-customer:5432/customer_db
    username: customer_user
    password: CustomerPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
