server:
  port: 8084

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://postgres-inventory:5432/inventory_db
    username: inventory_user
    password: InventoryPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
