server:
  port: 8089

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NOTIFICATION_EMAIL_USER}
    password: ${NOTIFICATION_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: redis
      port: 6379

notification:
  from: "Tu Tienda <no-reply@tutienda.pe>"
  subject:
    order-created: "¡Recibimos tu pedido! #{orderId}"
    order-confirmed: "¡Pago confirmado! Tu pedido #{orderId} está en proceso"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
