server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=orderdb;encrypt=true;trustServerCertificate=true
    username: order_user
    password: TuPasswordFuerte123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

customer-service:
  url: http://customer-service:8085

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
