server:
  port: 8083

spring:
  application:
    name: order-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=orderdb;encrypt=true;trustServerCertificate=true
    username: order_user
    password: TuPasswordFuerte123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

customer-service:
  url: http://localhost:8085

resilience4j:
  circuitbreaker:
    instances:
      customerClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      inventoryClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  retry:
    instances:
      customerClient:
        maxAttempts: 3
        waitDuration: 500ms
      pricingClient:
        maxAttempts: 3
        waitDuration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true




