server:
  port: 8092

spring:
  application:
    name: payment-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/payment_db
    username: payment_user
    password: PaymentPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

  instance:
    prefer-ip-address: true

