server:
  port: 8092

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://postgres-payment:5432/payment_db
    username: payment_user
    password: PaymentPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
