server:
  port: 8090

spring:
  application:
    name: pricing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/pricing_db
    username: pricing_user
    password: PricingPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 300000

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000

resilience4j:
  circuitbreaker:
    instances:
      productClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      productClient:
        maxAttempts: 3
        waitDuration: 500ms

product-service:
  url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
