server:
  port: 8090

spring:
  application:
    name: pricing-service

  datasource:
    url: jdbc:postgresql://postgres-pricing:5432/pricing_db
    username: pricing_user
    password: PricingPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 300000

product-service:
  url: http://product-service:8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
