server:
  port: 8081

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://product_user:Product123@${DB_HOST:localhost}:27017/ecommerce_product?authSource=${BD_MONG:ecommerce_product}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:redis-cache}
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

resilience4j:
  circuitbreaker:
    instances:
      inventoryClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      inventoryClient:
        maxAttempts: 3
        waitDuration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

