server:
  port: 8081

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/ecommerce_product?authSource=ecommerce_product
      username: product_user
      password: Product123
      auto-index-creation: true

  cache:
    type: redis
    redis:
      time-to-live: 300000

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000

inventory-service:
  url: http://inventory-service:8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
