server:
  port: 8091

spring:
  application:
    name: shipping-service

  datasource:
    url: jdbc:postgresql://postgres-shipping:5432/shipping_db
    username: shipping_user
    password: ShippingPass123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
